controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

position_controller:
  ros__parameters:
    joints:
      - FL_HFE
      - FL_KFE
      - FR_HFE
      - FR_KFE
      - HL_HFE
      - HL_KFE
      - HR_HFE
      - HR_KFE
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - FL_HFE
      - FL_KFE
      - FR_HFE
      - FR_KFE
      - HL_HFE
      - HL_KFE
      - HR_HFE
      - HR_KFE
    interface_name: velocity

effort_controller:
  ros__parameters:
    joints:
      - FL_HFE
      - FL_KFE
      - FR_HFE
      - FR_KFE
      - HL_HFE
      - HL_KFE
      - HR_HFE
      - HR_KFE
    interface_name: effort
